// GENERATED BY LOCALIZE-TS

export interface Translations {
  title: string;
  description: { description: string };
  multi_description: { description: string; multi: string };
  "nested.title": string;
  "nested.description": { description: string };
  "nested.multi_description": { description: string; multi: string };
  "nested.second_nested.title": string;
  "nested.second_nested.description": { description: string };
  "nested.second_nested.multi_description": { description: string; multi: string };
}
